name: Test-Build

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Node.js on the runner
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      # Install the newman CLI and newman-reporter-htmlextra globally
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Create directory to store test results
      - name: Make directory for results
        run: mkdir -p testResults

      # Run the Postman collection using Newman
      - name: Run POSTMAN collection
        run: newman run APITesting.postman_collection_last.json -e PROD.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/report.html --verbose

      # Upload the contents of the Test Results directory to the workflow artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: RunReports
          path: testResults/report.html
